apiVersion: v2
name: shared-app
description: A shared Helm chart for deploying applications to AKS
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: DevOps Team
    email: devops@company.com

keywords:
  - application
  - kubernetes
  - helm
  - aks
  - azure

home: https://github.com/company/shared-workflows
sources:
  - https://github.com/company/shared-workflows

dependencies: []

annotations:
  category: Application
  licenses: Apache-2.0