# Default values for shared-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  environment: dev
  applicationName: shared-app
  applicationType: java-springboot

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: myregistry.azurecr.io/shared-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Security context for the container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: shared-app.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: shared-app-tls
      hosts:
        - shared-app.local

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: APPLICATION_NAME
    value: "shared-app"

# ConfigMap configuration
configMap:
  enabled: true
  data:
    # Add your custom configuration here
    LOG_LEVEL: "info"
    DEBUG: "false"

# Secret configuration
secret:
  enabled: true
  data: {}
  # Database credentials
  database:
    username: "user"
    password: "password"
  # Security configuration
  security:
    jwtSecret: "your-jwt-secret-key-here"
  # API Keys
  apiKeys: {}
  # TLS certificates
  tls: {}
  # Application-specific secrets
  applicationSecrets: {}

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "javaapp"
  username: "user"
  password: "password"
  maxPoolSize: 10
  showSql: false

# Security configuration
security:
  corsEnabled: true
  allowedOrigins: "*"
  jwtSecret: "your-jwt-secret-key-here"
  jwtExpirationMs: 86400000

# Features configuration
features:
  cacheEnabled: true
  metricsEnabled: true
  auditEnabled: false
  debugMode: false

# Liveness probe configuration
livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Volume mounts
volumeMounts: []

# Volumes
volumes: []

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false

# Monitoring and observability
monitoring:
  enabled: true
  metricsPort: 8080
  metricsPath: "/actuator/prometheus"
  healthCheckInterval: 30
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"

# Tests
tests:
  enabled: false