# Production environment values for nodejs-backend3
global:
  environment: production
  applicationName: nodejs-backend3
  applicationType: nodejs

replicaCount: 3

image:
  repository: myregistry.azurecr.io/nodejs-backend3
  tag: "production-latest"

ingress:
  enabled: true
  pathPrefix: "backend3"
  proxyBodySize: "1024m"
  hosts:
    - host: production.mydomain.com

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

env:
  - name: ENVIRONMENT
    value: "production"
  - name: APPLICATION_NAME
    value: "nodejs-backend3"
  - name: PORT
    value: "3000"
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "warn"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

monitoring:
  enabled: true
  servicemonitor:
    enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 2
