# Staging environment values for java-backend2
global:
  environment: sqe
  applicationName: java-backend2
  applicationType: java-springboot

replicaCount: 2

image:
  repository: myregistry.azurecr.io/java-backend2
  tag: "sqe-latest"

ingress:
  enabled: true
  pathPrefix: "backend2"
  proxyBodySize: "1024m"
  hosts:
    - host: sqe.mydomain.com

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

env:
  - name: ENVIRONMENT
    value: "sqe"
  - name: APPLICATION_NAME
    value: "java-backend2"
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_PROFILES_ACTIVE
    value: "sqe"
  - name: LOG_LEVEL
    value: "INFO"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

monitoring:
  enabled: true
  servicemonitor:
    enabled: true
