{{- if .Values.ingress.enabled -}}
{{- $fullName := include "java-backend1.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $isProduction := eq .Values.global.environment "prod" -}}
{{- $isBlueGreenEnabled := and $isProduction .Values.global.blueGreenEnabled -}}
{{- $deploymentSlot := .Values.global.deploymentSlot | default "blue" -}}

# Main Production Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  {{- if $isBlueGreenEnabled }}
  namespace: default  # Main ingress in default namespace for Blue-Green
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
    {{- if $isBlueGreenEnabled }}
    active-slot: {{ $deploymentSlot }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/{{ .Values.ingress.pathPrefix }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.proxyBodySize }}"
    {{- if $isBlueGreenEnabled }}
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /({{ $.Values.ingress.pathPrefix }}/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                {{- if $isBlueGreenEnabled }}
                namespace: {{ $.Release.Namespace }}  # Point to current deployment namespace
                {{- end }}
                port:
                  number: {{ $svcPort }}
    {{- end }}


{{- end }}