{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "java-backend1.fullname" . }}-keyvault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azureKeyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.azureKeyVault.keyvaultName | quote }}
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.azureKeyVault.secrets }}
        - |
          objectName: {{ .objectName | quote }}
          objectType: secret
          {{- if .objectAlias }}
          objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
  {{- if .Values.azureKeyVault.secretObjects }}
  secretObjects:
    {{- range .Values.azureKeyVault.secretObjects }}
    - secretName: {{ .secretName | quote }}
      type: {{ .type | default "Opaque" | quote }}
      data:
        {{- range .data }}
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}