{{- if .Values.kubernetesSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubernetesSecrets.secretName | default "app-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
  annotations:
    # Spring Boot Profile-based secret management
    app.kubernetes.io/managed-by: "spring-boot-profiles"
    config.kubernetes.io/source: "helm-chart"
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  {{- range .Values.kubernetesSecrets.secrets }}
  {{ .key }}: {{ .value | default "placeholder" | b64enc }}
  {{- end }}
stringData:
  # Environment-specific configuration
  SPRING_PROFILES_ACTIVE: {{ .Values.global.environment | quote }}
  APPLICATION_NAME: {{ .Values.global.applicationName | quote }}
  APPLICATION_TYPE: {{ .Values.global.applicationType | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  
  # Spring Boot profile configuration
  SPRING_CONFIG_LOCATION: "classpath:application.yml,classpath:application-{{ .Values.global.environment }}.yml"
  SPRING_CONFIG_NAME: "application"
  
  # Kubernetes-native secret management indicator
  CONFIG_MANAGEMENT_TYPE: "kubernetes-secrets"
  SECRET_SOURCE: "helm-chart"
{{- end }}