apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-backend1.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
    {{- if and (eq .Values.global.environment "prod") .Values.global.blueGreenEnabled }}
    deployment-slot: {{ .Values.global.deploymentSlot | default "blue" }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "java-backend1.selectorLabels" . | nindent 4 }}
    {{- if and (eq .Values.global.environment "prod") .Values.global.blueGreenEnabled }}
    deployment-slot: {{ .Values.global.deploymentSlot | default "blue" }}
    {{- end }}