{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  
  # Database sensitive configuration
  {{- if .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  {{- end }}
  {{- if .Values.database.username }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  {{- end }}
  
  # Security sensitive configuration
  {{- if .Values.security.jwtSecret }}
  JWT_SECRET: {{ .Values.security.jwtSecret | b64enc }}
  {{- end }}
  
  # API Keys and other sensitive data
  {{- if .Values.secret.apiKeys }}
  {{- range $key, $value := .Values.secret.apiKeys }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  
  # SSL/TLS certificates (if needed)
  {{- if .Values.secret.tls }}
  {{- range $key, $value := .Values.secret.tls }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  
  # Additional application-specific secrets
  {{- if .Values.secret.applicationSecrets }}
  {{- range $key, $value := .Values.secret.applicationSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}