{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- $_ := include "shared-app.validateValues" . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shared-app.fullname" . }}-metrics
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "shared-app.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "shared-app.commonAnnotations" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "shared-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: {{ include "shared-app.metricsPath" . }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.basicAuth.enabled }}
      basicAuth:
        username:
          name: {{ .Values.metrics.serviceMonitor.basicAuth.secretName }}
          key: {{ .Values.metrics.serviceMonitor.basicAuth.usernameKey | default "username" }}
        password:
          name: {{ .Values.metrics.serviceMonitor.basicAuth.secretName }}
          key: {{ .Values.metrics.serviceMonitor.basicAuth.passwordKey | default "password" }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.bearerTokenSecret.enabled }}
      bearerTokenSecret:
        name: {{ .Values.metrics.serviceMonitor.bearerTokenSecret.name }}
        key: {{ .Values.metrics.serviceMonitor.bearerTokenSecret.key | default "token" }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- with .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}