# Staging environment values for nodejs-backend1
global:
  environment: sqe
  applicationName: nodejs-backend1
  applicationType: nodejs

replicaCount: 2

image:
  repository: myregistry.azurecr.io/nodejs-backend1
  tag: "sqe-latest"

ingress:
  enabled: true
  pathPrefix: "backend1"
  proxyBodySize: "1024m"
  hosts:
    - host: sqe.mydomain.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  - name: ENVIRONMENT
    value: "sqe"
  - name: APPLICATION_NAME
    value: "nodejs-backend1"
  - name: PORT
    value: "3000"
  - name: NODE_ENV
    value: "sqe"
  - name: LOG_LEVEL
    value: "info"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

monitoring:
  enabled: true
  servicemonitor:
    enabled: true
