# Default values for nodejs-backend1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  environment: dev
  applicationName: nodejs-backend1
  applicationType: nodejs

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: myregistry.azurecr.io/nodejs-backend1
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Security context for the container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 3000
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  pathPrefix: "backend1"
  proxyBodySize: "1024m"
  hosts:
    - host: dev.mydomain.com
    - host: staging.mydomain.com
    - host: production.mydomain.com

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: APPLICATION_NAME
    value: "nodejs-backend1"
  - name: PORT
    value: "3000"
  - name: NODE_ENV
    value: "development"
  - name: DEBUG_MODE
    value: "true"

# ConfigMap configuration
configMap:
  enabled: true
  data:
    LOG_LEVEL: "debug"
    DEBUG: "true"
    NODE_OPTIONS: "--max-old-space-size=512 --inspect=0.0.0.0:9229"
    ENABLE_DEBUGGING: "true"

# Liveness probe configuration (Node.js specific)
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration (Node.js specific)
readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Volume mounts
volumeMounts: []

# Volumes
volumes: []

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false

# Monitoring and observability
monitoring:
  enabled: false
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"

# Tests
tests:
  enabled: false



# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "30s"
    scrapeTimeout: "10s"
    honorLabels: true
    labels:
      app.kubernetes.io/component: metrics
    annotations: {}
    relabelings: []
    metricRelabelings: []