apiVersion: v2
name: java-app
description: A Helm chart for Java Spring Boot Application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - java
  - spring-boot
  - microservice

maintainers:
  - name: DevOps Team
    email: devops@company.com

dependencies:
  - name: shared-app
    version: "0.1.0"
    repository: "file://../shared-app"