# Default values for java-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  environment: dev
  applicationName: java-app
  applicationType: java-springboot

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: myregistry.azurecr.io/java-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Security context for the container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  pathPrefix: "java-app"
  proxyBodySize: "1024m"
  hosts:
    - host: java-app.local

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: APPLICATION_NAME
    value: "java-app"
  - name: SERVER_PORT
    value: "8080"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,metrics,prometheus,env,configprops,beans,mappings"
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: "always"

# ConfigMap configuration
configMap:
  enabled: true
  data:
    LOG_LEVEL: "DEBUG"
    DEBUG: "true"
    JAVA_OPTS: "-Xms512m -Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication"
    SPRING_PROFILES_INCLUDE: "actuator"

# Liveness probe configuration (Java Spring Boot specific)
livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration (Java Spring Boot specific)
readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Volume mounts
volumeMounts: []

# Volumes
volumes: []

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false

# Monitoring and observability
monitoring:
  enabled: false
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"

# Tests
tests:
  enabled: false

# Azure Key Vault integration
azureKeyVault:
  enabled: false
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  mountPath: "/mnt/secrets-store"
  secrets:
    - objectName: "db-password"
      objectAlias: "db-password"
    - objectName: "api-key"
      objectAlias: "api-key"
    - objectName: "jwt-secret"
      objectAlias: "jwt-secret"
  secretObjects:
    - secretName: "app-secrets"
      type: "Opaque"
      data:
        - objectName: "db-password"
          key: "db-password"
        - objectName: "api-key"  
          key: "api-key"
        - objectName: "jwt-secret"
          key: "jwt-secret"