# Development environment values for Java application

shared-app:
  enabled: true

global:
  environment: dev
  applicationName: java-app
  applicationType: java-springboot

# Development specific settings
image:
  tag: "dev-latest"
  pullPolicy: Always

# Lower resources for development
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

# Development specific environment variables
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: SPRING_DEVTOOLS_RESTART_ENABLED
    value: "true"
  - name: SPRING_H2_CONSOLE_ENABLED
    value: "true"

# Relaxed health checks for development
livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 60
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 5

# Development specific JVM options
jvm:
  opts: "-Xms256m -Xmx768m -XX:+UseG1GC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

# Azure Key Vault for development
azureKeyVault:
  enabled: true
  vaultName: "your-keyvault-dev"
  secrets:
    - secretName: database-url
      keyVaultSecretName: java-app-dev-database-url
    - secretName: database-password
      keyVaultSecretName: java-app-dev-database-password