# Production environment values for Java application

shared-app:
  enabled: true

global:
  environment: production
  applicationName: java-app
  applicationType: java-springboot

# Production specific settings
image:
  tag: "prod-latest"
  pullPolicy: IfNotPresent

# Higher resources for production
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Production specific environment variables
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: LOG_LEVEL
    value: "WARN"
  - name: SPRING_JPA_SHOW_SQL
    value: "false"
  - name: SPRING_DEVTOOLS_RESTART_ENABLED
    value: "false"

# Strict health checks for production
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

# Production specific JVM options
jvm:
  opts: "-Xms2g -Xmx3g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UseZGC"

# Replica count for production
replicaCount: 3

# Autoscaling for production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Azure Key Vault for production
azureKeyVault:
  enabled: true
  vaultName: "your-keyvault-prod"
  secrets:
    - secretName: database-url
      keyVaultSecretName: java-app-prod-database-url
    - secretName: database-password
      keyVaultSecretName: java-app-prod-database-password
    - secretName: jwt-secret
      keyVaultSecretName: java-app-prod-jwt-secret
    - secretName: redis-url
      keyVaultSecretName: java-app-prod-redis-url