# Development Environment Values for Java Spring Boot Application
shared-app:
  global:
    environment: dev

  # Lower resource requirements for dev
  replicaCount: 1

  image:
    pullPolicy: Always  # Always pull latest for dev

  # Environment variables
  env:
    - name: ENVIRONMENT
      value: "dev"
    - name: APPLICATION_NAME
      value: "java-app"
    - name: SPRING_PROFILES_ACTIVE
      value: "dev"
    - name: SERVER_PORT
      value: "8080"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"  # Expose all actuator endpoints in dev

  # ConfigMap for dev
  configMap:
    data:
      LOG_LEVEL: "debug"
      DEBUG: "true"
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"

  # Resource limits for dev
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  # Relaxed health checks for dev
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  # Ingress for dev
  ingress:
    enabled: true
    className: "nginx"
    pathPrefix: "java-app"
    proxyBodySize: "512m"
    annotations: {}
    hosts:
      - host: java-app-dev.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

  # No autoscaling in dev
  autoscaling:
    enabled: false

  # Monitoring enabled for testing
  monitoring:
    enabled: true

  # No pod disruption budget in dev
  podDisruptionBudget:
    enabled: false

  # Network policy disabled in dev for easier debugging
  networkPolicy:
    enabled: false