name: Deploy Java Backend 3 - Order Management Service

permissions:
  id-token: write
  contents: read
  actions: read

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'apps/java-backend3/**'
      - 'helm/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/java-backend3/**'
      - 'helm/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - sqe
          - production
      force_deploy:
        description: 'Force deployment even if no changes'
        required: false
        type: boolean
        default: false

jobs:
  # Deploy Java Backend 3 - Order Management Service
  deploy:
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'auto' }}
      application_name: java-backend3
      application_type: java-springboot
      build_context: apps/java-backend3
      dockerfile_path: apps/java-backend3/Dockerfile
      helm_chart_path: helm
      force_deploy: ${{ github.event.inputs.force_deploy == 'true' }}
    secrets: inherit