apiVersion: v2
name: nodejs-app
description: A Helm chart for Node.js Application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - nodejs
  - javascript
  - microservice

maintainers:
  - name: DevOps Team
    email: devops@company.com

dependencies:
  - name: shared-app
    version: "0.1.0"
    repository: "file://../shared-app"