# Staging Environment Values for Node.js Application

global:
  environment: staging

# Multiple replicas for testing load balancing
replicaCount: 2

image:
  pullPolicy: IfNotPresent

# Environment variables
env:
  - name: ENVIRONMENT
    value: "staging"
  - name: APPLICATION_NAME
    value: "nodejs-app"
  - name: NODE_ENV
    value: "staging"
  - name: PORT
    value: "3000"

# ConfigMap for staging
configMap:
  enabled: true
  data:
    LOG_LEVEL: "info"
    DEBUG: "false"
    NODE_OPTIONS: "--max-old-space-size=1024"

# Production-like resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Tighter health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Ingress configuration
ingress:
  enabled: true
  pathPrefix: "nodejs-app"
  proxyBodySize: "1024m"
  hosts:
    - host: nodejs-app-staging.company.com

# Enable autoscaling for staging
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Monitoring enabled
monitoring:
  enabled: true

# Pod disruption budget for availability testing
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network policy enabled for security testing
networkPolicy:
  enabled: true

# Anti-affinity for better distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - nodejs-app
          topologyKey: kubernetes.io/hostname

# Resource quotas and limits
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault