apiVersion: v2
name: aks-monitoring
description: Comprehensive monitoring solution for AKS cluster including Prometheus, Grafana, and Azure Monitor integration
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - monitoring
  - prometheus
  - grafana
  - azure-monitor
  - kubernetes
  - aks

maintainers:
  - name: Platform Team
    email: platform@company.com

dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki-stack
    version: "2.9.11"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled