{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Environment-specific configuration
  environment: {{ .Values.global.environment | quote }}
  application.name: {{ .Values.global.applicationName | quote }}
  application.type: {{ .Values.global.applicationType | quote }}
  # Java Spring Boot configuration
  server.port: {{ .Values.service.port | quote }}
  management.endpoints.web.exposure.include: "health,info,metrics,prometheus"
  management.endpoint.health.show-details: "always"
  management.server.port: {{ .Values.service.port | quote }}
  spring.profiles.active: {{ .Values.global.environment | quote }}
{{- end }}