# Main Application Configuration
# This is the base configuration file that Spring Boot loads first

spring:
  # Active profile is set via environment variable SPRING_PROFILES_ACTIVE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Application name
  application:
    name: ${APPLICATION_NAME:your-app-name}    # CHANGE THIS
  
  # Default main class settings
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  
  # Default JPA settings (will be overridden by profile-specific files)
  jpa:
    open-in-view: false
    show-sql: false
    
  # Default Jackson settings
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    default-property-inclusion: non_null

# Default server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-binding-errors: on_param
    include-exception: false
    include-message: always
    include-stacktrace: on_param

# Default logging configuration
logging:
  level:
    com.yourcompany.yourapp: ${LOG_LEVEL:INFO}    # CHANGE PACKAGE NAME
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Default management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      probes:
        enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true

# Application info
info:
  app:
    name: ${spring.application.name}
    description: Your Application Description    # CHANGE THIS
    version: ${APP_VERSION:1.0.0}
    encoding: ${file.encoding:UTF-8}
    java:
      version: ${java.version}