# Production Environment Configuration

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: never

# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db.company.com}:${DB_PORT:5432}/${DB_NAME:your_app_prod}
    username: ${DB_USERNAME:your_app_prod_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

# Logging for production
logging:
  level:
    com.yourcompany.yourapp: INFO               # CHANGE PACKAGE NAME
    org.springframework: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    root: WARN

# Management endpoints for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true

# Application configuration
app:
  name: Your App Name                          # CHANGE THIS
  version: ${APP_VERSION:1.0.0}
  environment: production
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourdomain.com}
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Content-Type,Authorization"
    allow-credentials: true