# Staging environment values for java-backend3
global:
  environment: staging
  applicationName: java-backend3
  applicationType: java-springboot

replicaCount: 2

image:
  repository: myregistry.azurecr.io/java-backend3
  tag: "staging-latest"

ingress:
  enabled: true
  pathPrefix: "backend3"
  proxyBodySize: "1024m"
  hosts:
    - host: staging.mydomain.com

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

env:
  - name: ENVIRONMENT
    value: "staging"
  - name: APPLICATION_NAME
    value: "java-backend3"
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_PROFILES_ACTIVE
    value: "staging"
  - name: LOG_LEVEL
    value: "INFO"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

monitoring:
  enabled: true
  servicemonitor:
    enabled: true
