apiVersion: v2
name: app-template
description: A Helm chart template for Spring Boot applications
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - spring-boot
  - microservice
  - java

maintainers:
  - name: Platform Team
    email: platform@company.com

# This is a template - customize these values:
# 1. Change 'name' to your application name
# 2. Update 'description' 
# 3. Update maintainers information