# Default values for Spring Boot application
# This is a YAML-formatted file.

global:
  environment: dev
  applicationName: your-app-name          # CHANGE THIS
  applicationType: java-springboot

replicaCount: 1

image:
  repository: your-app-name               # CHANGE THIS
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-app.local              # CHANGE THIS
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

configMap:
  enabled: true
  data: {}

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: APPLICATION_NAME
    value: "your-app-name"               # CHANGE THIS

monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: "30s"
    scrapeTimeout: "10s"
    honorLabels: true
    labels: {}
    annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}