name: 'Version Strategy'
description: 'Determines version tags based on environment and branch'

inputs:
  environment:
    description: 'Target environment'
    required: true
  application_name:
    description: 'Application name'
    required: true

outputs:
  version:
    description: 'Semantic version for the release'
    value: ${{ steps.version.outputs.version }}
  image_tag:
    description: 'Docker image tag'
    value: ${{ steps.version.outputs.image_tag }}
  helm_version:
    description: 'Helm chart version'
    value: ${{ steps.version.outputs.helm_version }}

runs:
  using: 'composite'
  steps:
    - name: Generate version using utilities
      id: version
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Environment: ${{ inputs.environment }}"
        
        # Load version utilities
        source ${{ github.workspace }}/scripts/version-utils.sh
        
        # Generate and set version outputs
        set_version_outputs "${{ inputs.environment }}" "${{ inputs.application_name }}"
      shell: bash