{{- if .Values.azureMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
  labels:
    {{- include "aks-monitoring.labels" . | nindent 4 }}
data:
  schema-version: "v1"
  config-version: "ver1"
  log-data-collection-settings: |-
    [log_collection_settings]
      [log_collection_settings.stdout]
        enabled = true
        exclude_namespaces = ["kube-system", "kube-public", "monitoring"]
      [log_collection_settings.stderr]
        enabled = true
        exclude_namespaces = ["kube-system", "kube-public", "monitoring"]
      [log_collection_settings.env_var]
        enabled = true
      [log_collection_settings.enrich_container_logs]
        enabled = false
      [log_collection_settings.collect_all_kube_events]
        enabled = false
  metric-collection-settings: |-
    [metric_collection_settings.collect_kube_system_pv_metrics]
      enabled = true
    [metric_collection_settings.collect_kube_system_pv_metrics]
      enabled = true
  alertable-metrics-configuration-settings: |-
    [alertable_metrics_configuration_settings.container_resource_utilization_thresholds]
      container_cpu_threshold_percentage = {{ .Values.alerting.warning.highCpuUsage.threshold }}
      container_memory_threshold_percentage = {{ .Values.alerting.warning.highMemoryUsage.threshold }}
    [alertable_metrics_configuration_settings.pv_utilization_thresholds]
      pv_usage_threshold_percentage = {{ .Values.alerting.warning.highDiskUsage.threshold }}
  integrations: |-
    [integrations.azure_network_policy_manager]
      collect_basic_metrics = false
      collect_advanced_metrics = false
---
{{- if .Values.azureMonitor.containerInsights.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: omsagent-configmap
  namespace: kube-system
  labels:
    {{- include "aks-monitoring.labels" . | nindent 4 }}
data:
  kube.conf: |
    # Fluentd config file for OMS Docker - cluster components (kubeAPI)
    <source>
      @type tail
      @id in_tail_kube_apiserver_audit
      multiline_flush_interval 5s
      path /var/log/kube-apiserver-audit.log
      pos_file /var/opt/microsoft/omsagent/state/kube-apiserver-audit.log.pos
      tag oms.api.kube-apiserver-audit
      format json
    </source>
    
    <source>
      @type tail
      @id in_tail_kube_controller_manager
      multiline_flush_interval 5s
      path /var/log/kube-controller-manager.log
      pos_file /var/opt/microsoft/omsagent/state/kube-controller-manager.log.pos
      tag oms.api.kube-controller-manager
      format kubernetes
    </source>
    
    <source>
      @type tail
      @id in_tail_kube_scheduler
      multiline_flush_interval 5s
      path /var/log/kube-scheduler.log
      pos_file /var/opt/microsoft/omsagent/state/kube-scheduler.log.pos
      tag oms.api.kube-scheduler
      format kubernetes
    </source>
{{- end }}
{{- end }}