name: 'Checkmarx Scan'
description: 'Checkmarx security scanning with SAST, SCA, and KICS'

inputs:
  application_name:
    description: 'Application name'
    required: true
  application_type:
    description: 'Application type (java-springboot, nodejs)'
    required: true
  build_context:
    description: 'Build context path'
    required: true
  checkmarx_enabled:
    description: 'Enable Checkmarx scanning'
    required: false
    default: 'true'
  checkmarx_url:
    description: 'Checkmarx server URL'
    required: false
  cx_tenant:
    description: 'Checkmarx tenant for OAuth2 authentication'
    required: false
  checkmarx_client_id:
    description: 'Checkmarx OAuth2 client ID'
    required: false
  checkmarx_client_secret:
    description: 'Checkmarx OAuth2 client secret'
    required: false
  checkmarx_scan_types:
    description: 'Checkmarx scan types (comma-separated: sca,sast,kics)'
    required: false
    default: 'sca,sast,kics'
  checkmarx_sast_preset:
    description: 'Checkmarx SAST preset'
    required: false
    default: 'Checkmarx Default'
  checkmarx_sca_resolver:
    description: 'Checkmarx SCA resolver'
    required: false
    default: 'auto'
  checkmarx_kics_platforms:
    description: 'Checkmarx KICS platforms to scan'
    required: false
    default: 'Docker,Kubernetes,Terraform'
  checkmarx_fail_build:
    description: 'Fail build on security issues'
    required: false
    default: 'true'
  checkmarx_high_threshold:
    description: 'High severity threshold'
    required: false
    default: '0'
  checkmarx_medium_threshold:
    description: 'Medium severity threshold'
    required: false
    default: '5'
  checkmarx_low_threshold:
    description: 'Low severity threshold'
    required: false
    default: '10'

outputs:
  scan_id:
    description: 'Checkmarx scan ID'
    value: ${{ steps.scan.outputs.scan_id }}
  sast_results:
    description: 'SAST scan results summary'
    value: ${{ steps.results.outputs.sast_results }}
  sca_results:
    description: 'SCA scan results summary'
    value: ${{ steps.results.outputs.sca_results }}
  kics_results:
    description: 'KICS scan results summary'
    value: ${{ steps.results.outputs.kics_results }}
  overall_results:
    description: 'Combined scan results summary'
    value: ${{ steps.results.outputs.overall_results }}
  scan_status:
    description: 'Overall Checkmarx scan status'
    value: ${{ steps.results.outputs.scan_status }}

runs:
  using: 'composite'
  steps:
    - name: Setup SCA Resolver
      if: inputs.checkmarx_enabled == 'true' && contains(inputs.checkmarx_scan_types, 'sca')
      shell: bash
      run: |
        if [[ "${{ inputs.application_type }}" == "java-springboot" && (-f "pom.xml" || -f "build.gradle") ]]; then
          echo "📦 Setup SCA for Java..."
          wget -q https://sca-downloads.s3.amazonaws.com/cli/2.7.2/ScaResolver-linux64.tar.gz
          tar -xzf ScaResolver-linux64.tar.gz && rm ScaResolver-linux64.tar.gz
          ./ScaResolver offline -r ".cxsca-results.json" -s ${{ inputs.build_context }} -n "${{ inputs.application_name }}"
        fi

    - name: Run Checkmarx AST
      id: scan
      if: inputs.checkmarx_enabled == 'true'
      uses: checkmarx/ast-github-action@86e9ae570a811f9a1fb85903647a307aa3bf6253
      with:
        project_name: ${{ inputs.application_name }}
        cx_server: ${{ inputs.checkmarx_url }}
        cx_user: ${{ inputs.checkmarx_client_id }}
        cx_password: ${{ inputs.checkmarx_client_secret }}
        cx_tenant: ${{ inputs.cx_tenant }}
        cx_client_secret: ${{ inputs.checkmarx_client_secret }}
        additional_params: --scan-types ${{ inputs.checkmarx_scan_types }} --report-format sarif --output-path . --sast-preset-name "${{ inputs.checkmarx_sast_preset }}"

    - name: Parse Results
      id: results
      if: inputs.checkmarx_enabled == 'true'
      shell: bash
      run: |
        SCAN_ID="CX-$(date +%Y%m%d%H%M%S)-${{ inputs.application_name }}"
        CRITICAL=0
        HIGH=0
        MEDIUM=0
        LOW=0
        
        # Parse SARIF results
        for file in $(find . -name "*.sarif" 2>/dev/null | head -5); do
          if [[ -f "$file" ]] && command -v jq >/dev/null 2>&1; then
            CRITICAL=$((CRITICAL + $(jq -r '[.runs[]?.results[]? | select(.level=="error")] | length' "$file" 2>/dev/null || echo "0")))
            HIGH=$((HIGH + $(jq -r '[.runs[]?.results[]? | select(.level=="warning")] | length' "$file" 2>/dev/null || echo "0")))
            MEDIUM=$((MEDIUM + $(jq -r '[.runs[]?.results[]? | select(.level=="note")] | length' "$file" 2>/dev/null || echo "0")))
            LOW=$((LOW + $(jq -r '[.runs[]?.results[]? | select(.level=="info")] | length' "$file" 2>/dev/null || echo "0")))
          fi
        done
        
        # Check thresholds
        STATUS="PASSED"
        [[ "$HIGH" -gt "${{ inputs.checkmarx_high_threshold }}" ]] && STATUS="FAILED"
        [[ "$MEDIUM" -gt "${{ inputs.checkmarx_medium_threshold }}" ]] && STATUS="FAILED"
        [[ "$LOW" -gt "${{ inputs.checkmarx_low_threshold }}" ]] && STATUS="FAILED"
        
        # Generate results summary
        SAST_RESULTS="H${HIGH}/M${MEDIUM}/L${LOW}"
        SCA_RESULTS="H${HIGH}/M${MEDIUM}/L${LOW}"
        KICS_RESULTS="H${HIGH}/M${MEDIUM}/L${LOW}"
        OVERALL_RESULTS="Total: H${HIGH}/M${MEDIUM}/L${LOW}"
        
        # Set outputs
        echo "scan_id=$SCAN_ID" >> $GITHUB_OUTPUT
        echo "sast_results=$SAST_RESULTS" >> $GITHUB_OUTPUT
        echo "sca_results=$SCA_RESULTS" >> $GITHUB_OUTPUT
        echo "kics_results=$KICS_RESULTS" >> $GITHUB_OUTPUT
        echo "overall_results=$OVERALL_RESULTS" >> $GITHUB_OUTPUT
        echo "scan_status=$STATUS" >> $GITHUB_OUTPUT
        
        echo "🔒 Checkmarx: $STATUS | Vulnerabilities: $CRITICAL critical, $HIGH high, $MEDIUM medium, $LOW low"

    - name: Upload Results
      if: always() && inputs.checkmarx_enabled == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: checkmarx-scan-results-${{ inputs.application_name }}
        path: |
          *.sarif
          .cxsca-results.json
        retention-days: 30

    - name: Check Build Status
      if: inputs.checkmarx_enabled == 'true' && inputs.checkmarx_fail_build == 'true'
      shell: bash
      run: |
        STATUS="${{ steps.results.outputs.scan_status }}"
        if [[ "$STATUS" == "FAILED" ]]; then
          echo "❌ Checkmarx scan failed - vulnerabilities exceed thresholds"
          exit 1
        else
          echo "✅ Checkmarx scan passed"
        fi

    - name: Skip (Disabled)
      if: inputs.checkmarx_enabled != 'true'
      shell: bash
      run: echo "⏭️ Checkmarx scan disabled"