# Default values for java-backend1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  environment: dev
  applicationName: my-app
  applicationType: java-springboot

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: myregistry.azurecr.io/my-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Security context for the container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8280
  targetPort: 8280
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  pathPrefix: "my-app"
  proxyBodySize: "1024m"
  hosts:
    - host: dev.mydomain.com
    - host: sqe.mydomain.com
    - host: preprod.mydomain.com
    - host: api.mydomain.com

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: APPLICATION_NAME
    value: "my-app"
  - name: SERVER_PORT
    value: "8280"
  - name: SPRING_PROFILES_ACTIVE
    value: "dev,common,actuator"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,metrics,prometheus"
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: "when-authorized"
  # Azure Key Vault Integration
  - name: AZURE_KEYVAULT_ENABLED
    value: "false"
  - name: AZURE_KEYVAULT_URI
    value: ""
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets
        key: tenant-id
        optional: true
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets
        key: client-id
        optional: true

# ConfigMap configuration
configMap:
  enabled: true
  data:
    LOG_LEVEL: "DEBUG"
    DEBUG: "true"
    JAVA_OPTS: "-Xms512m -Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication"
    SPRING_PROFILES_INCLUDE: "actuator"

# Liveness probe configuration (Java Spring Boot specific)
livenessProbe:
  enabled: true
  httpGet:
    path: /my-app/actuator/health/liveness
    port: 8280
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration (Java Spring Boot specific)
readinessProbe:
  enabled: true
  httpGet:
    path: /my-app/actuator/health/readiness
    port: 8280
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Volume mounts
volumeMounts: []

# Volumes
volumes: []

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false

# Monitoring and observability
monitoring:
  enabled: false
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8280"
    prometheus.io/path: "/my-app/actuator/prometheus"

# Tests
tests:
  enabled: false

# Azure Key Vault integration
azureKeyVault:
  enabled: false
  keyvaultName: "kv-my-app-dev"
  tenantId: ""
  userAssignedIdentityID: ""
  mountPath: "/mnt/secrets-store"
  secrets:
    - objectName: "mongodb-connection-string"
      objectAlias: "mongodb-connection-string"
    - objectName: "mongodb-health-connection-string"
      objectAlias: "mongodb-health-connection-string"
    - objectName: "jwt-secret"
      objectAlias: "jwt-secret"
    - objectName: "memcached-addresses"
      objectAlias: "memcached-addresses"
    - objectName: "redis-password"
      objectAlias: "redis-password"
    - objectName: "application-insights-key"
      objectAlias: "application-insights-key"
    - objectName: "oauth2-client-id"
      objectAlias: "oauth2-client-id"
    - objectName: "oauth2-client-secret"
      objectAlias: "oauth2-client-secret"
    - objectName: "cors-allowed-origins"
      objectAlias: "cors-allowed-origins"
  secretObjects:
    - secretName: "app-secrets"
      type: "Opaque"
      data:
        - objectName: "mongodb-connection-string"
          key: "mongodb-connection-string"
        - objectName: "mongodb-health-connection-string"
          key: "mongodb-health-connection-string"
        - objectName: "jwt-secret"
          key: "jwt-secret"
        - objectName: "memcached-addresses"
          key: "memcached-addresses"
        - objectName: "redis-password"
          key: "redis-password"
        - objectName: "application-insights-key"
          key: "application-insights-key"
        - objectName: "oauth2-client-id"
          key: "oauth2-client-id"
        - objectName: "oauth2-client-secret"
          key: "oauth2-client-secret"
        - objectName: "cors-allowed-origins"
          key: "cors-allowed-origins"

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "30s"
    scrapeTimeout: "10s"
    honorLabels: true
    labels:
      app.kubernetes.io/component: metrics
    annotations: {}
    relabelings: []
    metricRelabelings: []