apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-backend2.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend2.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "java-backend2.selectorLabels" . | nindent 4 }}