name: Configure Branch Protection

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/branch-protection.yml'

permissions:
  administration: write
  contents: read

jobs:
  setup-branch-protection:
    name: Setup Branch Protection Rules
    runs-on: ubuntu-latest
    steps:
      - name: Configure Branch Protection for Main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner: owner,
                repo: repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  checks: [
                    { context: 'Unit Tests' },
                    { context: 'Integration Tests' },
                    { context: 'SonarQube Security & Quality Scan' },
                    { context: 'Checkmarx Security Scan' },
                    { context: 'Dependency Vulnerability Scan' },
                    { context: 'Build & Package Application' },
                    { context: 'Security Policy Validation' },
                    { context: 'Container Security Scan' },
                    { context: 'Infrastructure Security Scan' },
                    { context: 'Quality Gate' }
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 2,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true,
                  require_last_push_approval: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log('✅ Branch protection rules configured for main branch');
            } catch (error) {
              console.error('❌ Failed to configure branch protection:', error.message);
              // Don't fail the workflow if branch protection can't be set
              // (might be due to insufficient permissions)
            }

      - name: Configure Branch Protection for Develop
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner: owner,
                repo: repo,
                branch: 'develop',
                required_status_checks: {
                  strict: true,
                  checks: [
                    { context: 'Unit Tests' },
                    { context: 'Integration Tests' },
                    { context: 'SonarQube Security & Quality Scan' },
                    { context: 'Checkmarx Security Scan' },
                    { context: 'Dependency Vulnerability Scan' },
                    { context: 'Build & Package Application' },
                    { context: 'Security Policy Validation' },
                    { context: 'Container Security Scan' },
                    { context: 'Infrastructure Security Scan' },
                    { context: 'Quality Gate' }
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log('✅ Branch protection rules configured for develop branch');
            } catch (error) {
              console.error('❌ Failed to configure branch protection for develop:', error.message);
              // Don't fail the workflow if branch protection can't be set
            }