name: Deploy Java Backend 1

on:
  push:
    branches: [ main, staging, dev ]
    paths:
      - 'apps/java-app/**'
      - 'helm/java-backend1/**'
      - '.github/workflows/deploy-java-backend1.yml'
      - '.github/workflows/shared-backend-deploy.yml'
      - '.github/actions/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
      force_deploy:
        description: 'Force deployment even if no changes detected'
        required: false
        type: boolean
        default: false
      skip_tests:
        description: 'Skip tests during build'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Perform a dry run deployment'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    uses: ./.github/workflows/shared-backend-deploy.yml
    with:
      backend_name: 'java-backend1'
      backend_type: 'java'
      environment: ${{ inputs.environment || '' }}
      force_deploy: ${{ inputs.force_deploy || false }}
      skip_tests: ${{ inputs.skip_tests || false }}
      dry_run: ${{ inputs.dry_run || false }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}