name: Deploy Java Backend 1 - User Management Service

permissions:
  id-token: write
  contents: read
  actions: read

on:
  push:
    branches:
      - dev
      - develop  # Legacy support
      - sqe
      - 'release/**'
    paths:
      - '**'
      - 'helm/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - dev
      - develop  # Legacy support
      - sqe
    paths:
      - '**'
      - 'helm/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - sqe
          - ppr
          - prod
      force_deploy:
        description: 'Force deployment even if no changes'
        required: false
        type: boolean
        default: false

jobs:
  # Deploy Java Backend 1 - User Management Service
  deploy:
    uses: ./.github/workflows/shared-deploy.yml@no-keyvault-shared-github-actions
    with:
      environment: ${{ github.event.inputs.environment || 'auto' }}
      application_name: java-backend1
      application_type: java-springboot
      build_context: .
      dockerfile_path: ./Dockerfile
      helm_chart_path: ./helm
      force_deploy: ${{ github.event.inputs.force_deploy == 'true' }}
    secrets: inherit